export const commonPage = {
	h1: 'h1',
	h5: 'h5',
	title: '.text-2xl',
	btn_login: '#dealls-navbar-login-btn',
	field_email: '#basic_email',
	field_password: '#basic_password',
	btn_sign_in: 'button[type="submit"]',
	popup_modal: '#modalConfirmationDeleteFolder > .modal-dialog > .modal-content > .modal-body',
	header_tab: '.container > ul',
	select_dropdown: '.select2-results__option',
	file_locator: 'input[type=file]',
	publish_table_id: '#documentListTable',
	dropdown_result: '.select2-results__options',
	progress_box: 'div.progress-box',
	data_table_length: 'label > select',
	noty_body: '.noty_body',
	icon_create_specification: '.icon-create-new-specification',
	body: 'body',
	search_input: 'label > input',
	processing_img: '.loading-icon',
	input_custom_product_type: '#inputAddProductType',
	add_product_to_table: '#submitAddProductTypeButton',
}