name: Cypress E2E

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Feature to run'
        required: true
        default: 'e2e:chrome'
        type: choice
        options:
          - e2e:chrome

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:latest
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            /root/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npm run cy:verify

      - name: Test site connectivity
        run: curl -Iv https://dealls.com

      - name: Restore Cypress Configuration
        run: |
          if [ -f "cypress.config.backup.js" ]; then
            mv cypress.config.backup.js cypress.config.js
          fi
          if [ -f "cypress/support/e2e.backup.js" ]; then
            mv cypress/support/e2e.backup.js cypress/support/e2e.js
          fi
          
      - name: Run Cypress E2E
        env:
          CYPRESS_BASE_URL: 'https://dealls.com/'
        run: echo "CYPRESS_BASE_URL=$CYPRESS_BASE_URL" && npm run ${{ github.event.inputs.feature }}

      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/
            cypress/results/
