name: Front-end CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    cypress-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: npm i

            - name: run cypress tests in chrome
              uses: cypress-io/github-action@v5
              timeout-minutes: 10
              with:
                  browser: chrome
                  record: true
                  build: npm run build
                  start: npm start
                  wait-on: 'http://localhost:3000'
              env:
                  CYPRESS_RECORD_KEY: 'https://dealls.com/'
