name: Cypress E2E

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Feature to run'
        required: true
        default: 'e2e:chrome'
        type: choice
        options:
          - e2e:chrome

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fix Permissions
        run: chmod -R 755 /var/lib/apt/lists/partial

      - name: Resolve Duplicate Configurations
        run: |
          sudo sed -i '/microsoft-edge-stable.list/d' /etc/apt/sources.list.d/microsoft-edge.list

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            /root/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npm run cy:verify

      - name: Restore Cypress Configuration
        run: |
          if [ -f "cypress.config.backup.js" ]; then
            mv cypress.config.backup.js cypress.config.js
          fi
          if [ -f "cypress/support/e2e.backup.js" ]; then
            mv cypress/support/e2e.backup.js cypress/support/e2e.js
          fi

      - name: Test site connectivity
        run: |
          apt-get update && apt-get install -y curl
          curl -Iv https://dealls.com

      - name: Run Cypress E2E
        env:
          CYPRESS_BASE_URL: 'https://dealls.com/'
        run: echo "CYPRESS_BASE_URL=$CYPRESS_BASE_URL" && npm run ${{ github.event.inputs.feature }}

      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/
            cypress/results/
